server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Insurance
      auto-index-creation: true
      connection-pool-size: 10
      connect-timeout: 5000
      socket-timeout: 3000
      max-wait-time: 1500
      max-connection-life-time: 30000
  security:
    user:
      name: admin
      password: admin123

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method